import { ICardProps } from "../components/Card/interface";

export const carros: ICardProps[] = [
  {
    id: "1",
    title: "Mercedes Benz A 200",
    img: "/src/assets/Cars/carPhoto.png",
    description:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
    userName: "Usuário 1",
    km: "100.000 km",
    year: "2010",
    value: 15000,
    fipePrice: 30000,
    createdAt: "2023-06-12",
  },
  {
    id: "2",
    title: "Carro 2",
    img: "/src/assets/Cars/car1.png",
    description:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
    userName: "Usuário 2",
    km: "50.000 km",
    year: "2015",
    value: 25000,
    fipePrice: 30000,
    createdAt: "2023-06-12",
  },
  {
    id: "3",
    title: "Carro 3",
    img: "/src/assets/Cars/car2.png",
    description:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
    userName: "Usuário 3",
    km: "30.000 km",
    year: "2020",
    value: 35000,
    fipePrice: 30000,
    createdAt: "2023-06-07",
  },
  {
    id: "4",
    title: "Carro 4",
    img: "/src/assets/Cars/car3.png",
    description:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
    userName: "Usuário 4",
    km: "80.000 km",
    year: "2012",
    value: 18000,
    fipePrice: 30000,
    createdAt: "2023-05-10",
  },
  {
    id: "5",
    title: "Carro 5",
    img: "/src/assets/Cars/car4.png",
    description:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
    userName: "Usuário 5",
    km: "10.000 km",
    year: "2021",
    value: 40000,
    fipePrice: 30000,
    createdAt: "2023-05-12",
  },
  {
    id: "6",
    title: "Carro 6",
    img: "/src/assets/Cars/car2.png",
    description:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
    userName: "Usuário 6",
    km: "20.000 km",
    year: "2019",
    value: 30000,
    fipePrice: 30000,
    createdAt: "2023-05-25",
  },
  {
    id: "7",
    title: "Carro 7",
    img: "/src/assets/Cars/car1.png",
    description:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
    userName: "Usuário 7",
    km: "60.000 km",
    year: "2013",
    value: 20000,
    fipePrice: 30000,
    createdAt: "2023-06-01",
  },
  {
    id: "8",
    title: "Carro 8",
    img: "/src/assets/Cars/car2.png",
    description:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
    userName: "Usuário 8",
    km: "40.000 km",
    year: "2017",
    value: 28000,
    fipePrice: 30000,
    createdAt: "2023-05-1",
  },
  {
    id: "9",
    title: "Carro 9",
    img: "/src/assets/Cars/carPhoto.png",
    description:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
    userName: "Usuário 9",
    km: "100.000 km",
    year: "2010",
    value: 15000,
    fipePrice: 30000,
    createdAt: "2023-03-10",
  },
  {
    id: "10",
    title: "Carro 10",
    img: "/src/assets/Cars/car4.png",
    description:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
    userName: "Usuário 10",
    km: "60.000 km",
    year: "2013",
    value: 20000,
    fipePrice: 30000,
    createdAt: "2023-03-10",
  },
  {
    id: "11",
    title: "Carro 8",
    img: "/src/assets/Cars/car3.png",
    description:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
    userName: "Usuário 11",
    km: "40.000 km",
    year: "2017",
    value: 28000,
    fipePrice: 30000,
    createdAt: "2023-02-10",
  },
  {
    id: "12",
    title: "Carro 12",
    img: "/src/assets/Cars/car1.png",
    description:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
    userName: "Usuário 12",
    km: "100.000 km",
    year: "2010",
    value: 15000,
    fipePrice: 30000,
    createdAt: "2023-01-1",
  },
];
