interface Car {
  id: string;
  title: string;
  img: string;
  description: string;
  userName: string;
  km: string;
  year: string;
  value: number;
}

export const carros: Car[] = [
  {
    id: "1",
    title: "Mercedes Benz A 200 CGI ADVANCE SEDAN Mercedes Benz A 200",
    img: "/src/assets/carPhoto.png",
    description: "Descrição do Carro 1",
    userName: "Usuário 1",
    km: "100.000 km",
    year: "2010",
    value: 15000,
  },
  {
    id: "2",
    title: "Carro 2",
    img: "caminho/para/imagem2.jpg",
    description: "Descrição do Carro 2",
    userName: "Usuário 2",
    km: "50.000 km",
    year: "2015",
    value: 25000,
  },
  {
    id: "3",
    title: "Carro 3",
    img: "caminho/para/imagem3.jpg",
    description: "Descrição do Carro 3",
    userName: "Usuário 3",
    km: "30.000 km",
    year: "2020",
    value: 35000,
  },
  {
    id: "4",
    title: "Carro 4",
    img: "caminho/para/imagem4.jpg",
    description: "Descrição do Carro 4",
    userName: "Usuário 4",
    km: "80.000 km",
    year: "2012",
    value: 18000,
  },
  {
    id: "5",
    title: "Carro 5",
    img: "caminho/para/imagem5.jpg",
    description: "Descrição do Carro 5",
    userName: "Usuário 5",
    km: "10.000 km",
    year: "2021",
    value: 40000,
  },
  {
    id: "6",
    title: "Carro 6",
    img: "caminho/para/imagem6.jpg",
    description: "Descrição do Carro 6",
    userName: "Usuário 6",
    km: "20.000 km",
    year: "2019",
    value: 30000,
  },
  {
    id: "7",
    title: "Carro 7",
    img: "caminho/para/imagem7.jpg",
    description: "Descrição do Carro 7",
    userName: "Usuário 7",
    km: "60.000 km",
    year: "2013",
    value: 20000,
  },
  {
    id: "8",
    title: "Carro 8",
    img: "caminho/para/imagem8.jpg",
    description: "Descrição do Carro 8",
    userName: "Usuário 8",
    km: "40.000 km",
    year: "2017",
    value: 28000,
  },
  {
    id: "9",
    title: "Carro 9",
    img: "caminho/para/imagem1.jpg",
    description: "Descrição do Carro 9",
    userName: "Usuário 9",
    km: "100.000 km",
    year: "2010",
    value: 15000,
  },
  {
    id: "10",
    title: "Carro 10",
    img: "caminho/para/imagem7.jpg",
    description: "Descrição do Carro 10",
    userName: "Usuário 10",
    km: "60.000 km",
    year: "2013",
    value: 20000,
  },
  {
    id: "11",
    title: "Carro 8",
    img: "caminho/para/imagem8.jpg",
    description: "Descrição do Carro 11",
    userName: "Usuário 11",
    km: "40.000 km",
    year: "2017",
    value: 28000,
  },
  {
    id: "12",
    title: "Carro 12",
    img: "caminho/para/imagem1.jpg",
    description: "Descrição do Carro 12",
    userName: "Usuário 12",
    km: "100.000 km",
    year: "2010",
    value: 15000,
  },
];
